# Generated by Django 3.0.2 on 2020-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('PWN', 'Pwn'), ('CRYPTO', 'Cryptography')], max_length=15)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.IntegerField(default=0)),
                ('flag', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
