# Generated by Django 3.0.2 on 2020-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('PWN', 'PWN'), ('CRYPTO', 'CRYPTO'), ('PPC', 'PPC'), ('WEB', 'WEB'), ('STEGANO', 'STEGANO'), ('REVERSE', 'REVERSE'), ('JOY', 'JOY'), ('ADMIN', 'ADMIN')], max_length=15),
        ),
    ]
