# Generated by Django 3.0.2 on 2020-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='classification',
            field=models.CharField(blank=True, choices=[('SCH', 'Школьники'), ('UNI', 'Студенты'), ('OTH', 'Вне зачёта')], max_length=15),
        ),
    ]
